[package]
name = "tensorflow-sys"
version = "0.16.0"
license = "Apache-2.0"
authors = [
  "Adam Crume <acrume@google.com>",
  "Ivan Ukhov <ivan.ukhov@gmail.com>",
]
description = "The package provides bindings to TensorFlow."
documentation = "https://tensorflow.github.io/rust"
homepage = "https://github.com/tensorflow/rust"
repository = "https://github.com/tensorflow/rust"
build = "build.rs"
links = "tensorflow"
edition = "2018"

[dependencies]
libc = "0.2.43"

[build-dependencies]
curl = "0.4.19"
flate2 = "1.0.4"
pkg-config = "0.3.14"
semver = "0.9.0"
tar = "0.4.19"

[features]
tensorflow_gpu = []
# This is for testing purposes; users should not use this.
examples_system_alloc = []
